# -*- coding: utf-8 -*-
"""Naive Bayes Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeKMvzPyPDAkq15V30vUCDaPIWxeSoYK
"""

import pandas as pd
from collections import Counter
import numpy as np
#Create the dataset
data = pd.DataFrame({"MessageID": ["M1", "M2", "M3", "M4"],"MessageText": ["buy cheap now","limited offer buy","meet me now","let's catch up"],
                     "Class": ["Spam", "Spam", "Not Spam", "Not Spam"]})
print(data)

#Extract all unique words from the messages
def tokenize(text):
    return text.lower().split()
all_words = []
for msg in data["MessageText"]:
    all_words.extend(tokenize(msg))
vocab = sorted(set(all_words))
V = len(vocab)
print("Vocabulary:", vocab)
print("Vocabulary size V =", V)

#Calculate word frequencies for each class
spam_msgs = data[data["Class"] == "Spam"]["MessageText"]
ham_msgs = data[data["Class"] == "Not Spam"]["MessageText"]
spam_words = []
ham_words = []
for msg in spam_msgs:
    spam_words.extend(tokenize(msg))
for msg in ham_msgs:
    ham_words.extend(tokenize(msg))
spam_count = Counter(spam_words)
ham_count = Counter(ham_words)
print("Spam word frequencies:", spam_count)
print("Not Spam word frequencies:", ham_count)
total_spam_words = sum(spam_count.values())
total_ham_words = sum(ham_count.values())
print("Total spam words =", total_spam_words)
print("Total ham words  =", total_ham_words)

#Add the new message: "buy now"
new_message = "buy now"
new_tokens = tokenize(new_message)
print("New message tokens:", new_tokens)

#Calculate prior probabilities
num_spam = len(spam_msgs)
num_ham = len(ham_msgs)
total_msgs = len(data)
P_spam = num_spam / total_msgs
P_ham = num_ham / total_msgs
print("P(Spam) =", P_spam)
print("P(Not Spam) =", P_ham)

#Apply Multinomial Naïve Bayes with Laplace smoothing
def P_w_given_C(word, count_dict, total_words, V):
    return (count_dict.get(word, 0) + 1) / (total_words + V)
#Compute likelihoods
spam_likelihood = P_spam
ham_likelihood = P_ham
for w in new_tokens:
    spam_likelihood *= P_w_given_C(w, spam_count, total_spam_words, V)
    ham_likelihood *= P_w_given_C(w, ham_count, total_ham_words, V)
print("Likelihood Spam (unnormalized) =", spam_likelihood)
print("Likelihood Not Spam (unnormalized) =", ham_likelihood)

#Classification
if spam_likelihood > ham_likelihood:
    prediction = "Spam"
else:
    prediction = "Not Spam"
print("FINAL CLASSIFICATION:", prediction)

"""PART 2"""

#Consider the dataset
data = {
    'text':[
        'Free money now',
        'Call now to claim your prize',
        'Meet me at the park',
        'Lets catch up later',
        'Win a new car today!',
        'Lunch plans?',
        'Congratulations! You won a lottery',
        'Can you send me the report?',
        'Exclusive offer for you',
        'Are you coming to the meeting?'],
    'label':['spam','spam','not sapm','not spam','spam','not spam','spam','not spam','spam', 'not spam']}
df = pd.DataFrame(data)
print(df)

#Map labels to Numerical Values
df['label'] = df['label'].map({'spam':1, 'not sapm':0})

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

#split the data into training and testing
X = df['text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#Vectorize the text Data
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

#Train the NB model
model = MultinomialNB()
model.fit(X_train_vec, y_train)

#Predictions and Evaluate accuracy
y_pred = model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy:{accuracy *100:.2f}%\n")

#Predict the message: "Congratulations, you've won a free vacation"
custom_message = ["Congratulations, you've won a free vacation"]
print(custom_message)
custom_message_vec = vectorizer.transform(custom_message)
prediction = model.predict(custom_message_vec)
print("Prediction for custom message:", "spam" if prediction[0]==1 else 'Not Spam')